-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: flake8
    -   id: check-symlinks
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.5.4
    hooks:
    -   id: shell-lint
    -   id: shellcheck
