repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: flake8
    -   id: check-symlinks
-   repo: https://github.com/ambv/black
    sha: 18.5b0
    hooks:
    -   id: black
        args: [--line-length=79]
