---
language: python
python: ["2.7", "3.4", "3.5", "3.6"]
dist: trusty
sudo: false
cache:
  - pip
matrix:
  include:
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=bandit
    - python: "3.6"
      env: TOXENV=pre-commit
  allow_failures:
    - python: "3.2"

install:
  - git clone --depth 1 https://github.com/sstephenson/bats "$HOME/bats"
  - pip install tox-travis | cat

env:
    PATH: "$PATH:$HOME/bats/bin"
script:
  - tox

notifications:
  email: false
