---
language: python
python: ["2.7", "3.2", "3.3", "3.4", "3.5"]
dist: trusty
sudo: false
cache:
  - pip
matrix:
  include:
    - python: "3.5"
      env: TOXENV=docs
  allow_failures:
    - python: "3.2"

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
